name: Deployment Notification

on: pull_request

jobs:
  deployment_notification:
    runs-on: ubuntu-latest
    name: Decentraland Explorer Deployment Notification
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'This branch can be previewed at [https://explorer.decentraland.zone/branch/${{ github.ref }}/index.html](https://explorer.decentraland.zone/branch/${{ github.ref }}/index.html)'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
